# Generated by Django 6.0.3 on 2026-03-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_instauser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('InstaUser_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser')),
                ('tagged_users', models.ManyToManyField(blank=True, null=True, related_name='tagged_posts', to='myapp.instauser')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
