# Generated by Django 6.0.3 on 2026-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_instapost_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instapost',
            old_name='InstaUser_FK',
            new_name='user',
        ),
        migrations.AddField(
            model_name='instapost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
