# Generated by Django 6.0.3 on 2026-04-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_instauser_fk_instapost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to='myapp.instauser')),
                ('Following_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following_person', to='myapp.instauser')),
            ],
        ),
    ]
