# Generated by Django 6.0.3 on 2026-04-14 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_followusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=40)),
                ('notification_type', models.CharField(choices=[('follow', 'follow'), ('like', 'like'), ('comment', 'comment')], max_length=20)),
                ('read_status', models.CharField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.instapost')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_notification', to='myapp.instauser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='myapp.instauser')),
            ],
        ),
    ]
