# Generated by Django 6.0.3 on 2026-04-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_instrareels'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_unlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='myapp.instapost')),
                ('reel_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_reel', to='myapp.instrareels')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='myapp.instauser')),
            ],
            options={
                'unique_together': {('user_fk', 'post_fk', 'reel_fk')},
            },
        ),
    ]
