# Generated by Django 6.0.3 on 2026-04-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_notification_post_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.instrareels'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.instapost'),
        ),
    ]
