# Generated by Django 6.0.3 on 2026-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notification_reel_fk_alter_notification_post_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='otp',
            field=models.IntegerField(blank=True, default=1234, max_length=4, null=True),
        ),
    ]
