# Generated by Django 6.0.3 on 2026-04-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_instauser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='otp',
            field=models.IntegerField(blank=True, default=1234, null=True),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='myapp.instapost')),
                ('reel_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_reel', to='myapp.instrareels')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='myapp.instauser')),
            ],
        ),
    ]
