# Generated by Django 6.0.3 on 2026-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
